# Generated by Django 5.2.4 on 2025-07-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stok', models.PositiveIntegerField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunler/')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kategori')),
            ],
        ),
    ]
